/*!
 * jQvalidation-laravel.js
 * Version ${pkg.version} - built ${now.format('ddd, MMM Do YYYY, h:mm a')}
 * https://github.com/happyDemon/jQvalidation-laravel
 * Maxim Kerstens - <maxim.kerstens@gmail.com>
 * MIT Licensed
 */

// The source code below is generated by babel as
// jQvalidation-laravel is written in ECMAScript 6

